/*
 * themes-list.js
 * GENERATED by tools/build_themes.py from the themes/ folder.
 * Do not edit by hand.
 */

/** Theme id, display name and group, in picker order. */
window.QUIZ_THEMES = [
  ["classic", "Classic", "Simple & pastel"],
  ["blush", "Blush", "Simple & pastel"],
  ["peach", "Peach", "Simple & pastel"],
  ["butter", "Butter", "Simple & pastel"],
  ["sage", "Sage", "Simple & pastel"],
  ["mint", "Mint", "Simple & pastel"],
  ["sky", "Sky", "Simple & pastel"],
  ["lavender", "Lavender", "Simple & pastel"],
  ["mist", "Mist", "Simple & pastel"],
  ["professional", "Professional", "Simple & pastel"],
  ["whiteboard", "Whiteboard", "Simple & pastel"],
  ["pastel", "Pastel", "Playful"],
  ["lego", "Lego", "Playful"],
  ["clay", "Clay", "Playful"],
  ["comic", "Comic book", "Playful"],
  ["anime", "Anime", "Playful"],
  ["watercolor", "Watercolor", "Playful"],
  ["university", "University", "Subjects"],
  ["history", "Indian History", "Subjects"],
  ["universe", "Universe", "Subjects"],
  ["maths", "Maths", "Subjects"],
  ["vmaths", "Vedic Maths", "Subjects"],
  ["geometry", "Geometry", "Subjects"],
  ["art", "Art", "Subjects"],
  ["music", "Music", "Subjects"],
  ["brain", "Healthy Brain", "Subjects"],
  ["social", "Talk to People", "Subjects"],
  ["vedic", "Vedic", "Wellbeing & culture"],
  ["ayurveda", "Ayurveda", "Wellbeing & culture"],
  ["sanskrit", "Sanskrit", "Wellbeing & culture"],
  ["yoga", "Yoga", "Wellbeing & culture"],
  ["meditation", "Meditation", "Wellbeing & culture"],
  ["exercise", "Exercise", "Wellbeing & culture"],
  ["food", "Food", "Wellbeing & culture"]
];

/** The Google Fonts every theme needs, in one request. */
window.QUIZ_THEME_FONTS_URL =
  "https://fonts.googleapis.com/css2?" +
  [
    "family=Instrument+Sans:wght@400;500;600",
    "family=Source+Serif+4:ital,opsz,wght@0,8..60,400;0,8..60,600;1,8..60,400",
    "family=Nunito:wght@400;600;700",
    "family=Inter:wght@400;500;600",
    "family=Patrick+Hand",
    "family=Caveat:wght@600",
    "family=Quicksand:wght@500;600;700",
    "family=Fredoka:wght@400;500;600",
    "family=Comic+Neue:wght@400;700",
    "family=Bangers",
    "family=M+PLUS+Rounded+1c:wght@400;500;700",
    "family=EB+Garamond:wght@400;500;600",
    "family=Cormorant+Garamond:wght@500;600",
    "family=Exo+2:wght@400;600",
    "family=Lexend:wght@400;500",
    "family=Baloo+2:wght@400;600",
    "family=Josefin+Sans:wght@400;600",
    "family=Permanent+Marker",
    "family=Playfair+Display:wght@500;700",
    "family=Poppins:wght@400;500;600",
    "family=Marcellus",
    "family=Lora:wght@400;600",
    "family=Barlow:wght@400;600",
    "family=Barlow+Condensed:wght@600",
    "display=swap",
  ].join("&");
